### PR TITLE
Add support for linked worktrees

### LINKED ISSUE #25: Support linked worktrees
[findRepo](https://github.com/rwjblue/git-repo-info/blob/master/index.js#L22-L24) does not check for [linked worktrees](https://git-scm.com/docs/git-worktree).  A linked worktree will have a `.git` file that points to the worktree path within the main repo's `.git` dir.

This issue prevents, among other things, running two versions of ember data in the same repo.

```
# within ember data
git worktree add base
cd base
npm install && bower install
ember build
# => Could not require 'ember-cli-build.js': Cannot read property 'slice' of null
# => TypeError: Could not require 'ember-cli-build.js': Cannot read property 'slice' of null
```

### PR DESCRIPTION
**Pull request by hjdivad**
Within a linked worktree (ie a worktree created via `git worktree add`) `.git`
is a file that points to a worktree git dir (within the repo's `.git`).  This
directory contains `HEAD` and a file that contains the path to the repo's git
dir.

`findRepo` now returns a POJO with two paths: the worktree git dir and the
common git dir.  For the base work tree, these paths will be the same.  For a
linked worktree, they will be different, eg

``` javascript
{
  worktreeGitDir: '<GIT_DIR>/worktrees/base',
  commonGitDir:   '<GIT_DIR>',
}
```

[Fix #25]

### CODE REVIEW

**Comment by rwjblue** [comment]
Thanks @hjdivad!

**Comment by rwjblue** [comment]
Published as v1.3.0

**Comment by john-kurkowski** [comment]
This is a breaking change, right? A public function used to return a string, now a POJO? Should this be v2.0.0?

**EDIT:** No _public_ function changed here. My bad.

**Comment by rwjblue** [comment]
@john-kurkowski - Hmm, can you please open an issue describing where you are hitting breaking change here?

The change (unless I have completely misread before merge) is that `require('git-repo-info')._findRepo` has a different return value, but that leading underscore generally indicates private API and the documented usage is  `require('git-repo-info')()` which has the same return value...

**Comment by john-kurkowski** [comment]
Oops, you're right. We were using the private method. Thank you for the quick response. Never mind!

**Comment by hjdivad** [comment]
Thanks for the fast merge @rwjblue! 🎉 🍻

**Pull request merged**
