### PR TITLE
SHA for submodule repos

### PR DESCRIPTION
**Pull request by PratheepV**
Hi,

SHA for submodule repos is not fetching.

I have the repo as a submodule. Its not taking the version for that. Please try to review my changes.

### CODE REVIEW

**Comment by rwjblue** [comment]
Can you:
- Provide me the local git commands to use so that I can create a repo that emulates the issue you are facing?
- Add a test so we can make sure not to break it in the future?

**Comment by PratheepV** [comment]
@rwjblue , Hey I added the specs for submodule repo. Please review my changes.

**Comment by jrowlingson** [comment]
@rwjblue what is the status on this?

**Comment by bastianlb** [comment]
+1, having trouble with submodules.

**Comment by rwjblue** [comment]
Will need a rebase (also sorry for the delay here)...

**Comment by rwjblue** [comment]
@PratheepV - Ping?  Would you mind rebasing and updating for latest changes on master?

**Comment by PratheepV** [comment]
@rwjblue  Please check now...

**Comment by hjdivad** [comment]
I believe this is already covered in https://github.com/rwjblue/git-repo-info/blob/master/tests/index.js#L88-L97 and https://github.com/rwjblue/git-repo-info/blob/master/tests/index.js#L304-L326

@PratheepV have you check with v1.3.1?  Basic submodule support should work.  IIRC the current issues are
1. `root` is not correctly computed (but SHA &c. are)
2. linked worktrees within submodules almost certainly don't work.

**Comment by PratheepV** [comment]
@hjdivad yeah... I missed it. @rwjblue I am closing it.

**Pull request closed without merging**
